name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar credenciales de AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
        aws-region: us-east-1

    # Iniciar sesión en Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Construir y subir imagen
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sales-service-repo
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Desplegar en EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN,AWS_REGION
        script: |
          # 1. Configurar credenciales en el host para poder hacer login
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set aws_session_token $AWS_SESSION_TOKEN
          aws configure set default.region $AWS_REGION
          
          # 2. Login en ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 303339717226.dkr.ecr.us-east-1.amazonaws.com
          
          # 3. Limpieza
          docker stop sales-service || true
          docker rm sales-service || true
          
          # 4. Descarga
          docker pull 303339717226.dkr.ecr.us-east-1.amazonaws.com/sales-service-repo:latest
          
          # 5. Ejecución (PASANDO CREDENCIALES AL CONTENEDOR)
          docker run -d -p 8001:8000 \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
            -e AWS_REGION="us-east-1" \
            -e APP_ENVIRONMENT="production" \
            -e TABLE_NOTES="SalesNotes" \
            -e TABLE_ITEMS="SalesNoteItems" \
            -e SNS_TOPIC_ARN="arn:aws:sns:us-east-1:303339717226:NewSalesNoteTopic" \
            --name sales-service \
            303339717226.dkr.ecr.us-east-1.amazonaws.com/sales-service-repo:latest