name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Se activa cuando hace push a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar credenciales de AWS (Usando los secretos que configuró)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
        aws-region: us-east-1

    # 3. Iniciar sesión en Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 4. Construir la imagen Docker y subirla a ECR
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sales-service-repo
        IMAGE_TAG: latest
      run: |
        # Construir la imagen
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Subir la imagen a AWS
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"


    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 303339717226.dkr.ecr.us-east-1.amazonaws.com
          
          docker stop sales-service || true
          docker rm sales-service || true
          docker pull 303339717226.dkr.ecr.us-east-1.amazonaws.com/sales-service-repo:latest
          
          docker run -d -p 8001:8000 \
            -e AWS_REGION="us-east-1" \
            -e APP_ENVIRONMENT="production" \
            -e TABLE_NOTES="SalesNotes" \
            -e TABLE_ITEMS="SalesNoteItems" \
            -e SNS_TOPIC_ARN="arn:aws:sns:us-east-1:303339717226:NewSalesNoteTopic" \
            --name sales-service \
            303339717226.dkr.ecr.us-east-1.amazonaws.com/sales-service-repo:latest